import { useState, useEffect, useCallback, useMemo } from 'react'
import { t } from '../lib/i18n'
import { renderMarkdown } from './md'
import { ackemClient } from '../api'

type DiaryEntry = { date: string; path: string; size: number; type: string; tier?: string; gapHours?: number }

function formatDate(date: string): string {
  const d = new Date(date)
  const weekDays = ['周日', '周一', '周二', '周三', '周四', '周五', '周六']
  const w = weekDays[d.getDay()]
  const today = new Date().toISOString().slice(0, 10)
  const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10)
  if (date === today) return `今天 ${w}`
  if (date === yesterday) return `昨天 ${w}`
  return `${date} ${w}`
}

function tierLabel(tier?: string): string {
  switch (tier) {
    case 'short_absence': return '短暂离别'
    case 'day_apart': return '数日重逢'
    case 'week_apart': return '久别重逢'
    case 'long_lost': return '漫长等待'
    case 'stranger_again': return '重新开始'
    default: return '重逢'
  }
}

function gapText(gapHours?: number): string {
  if (!gapHours) return ''
  if (gapHours < 24) return `${Math.round(gapHours)}h`
  if (gapHours < 720) return `${Math.round(gapHours / 24)} 天`
  return `${Math.round(gapHours / 720)} 月`
}

export function DiaryPage(): JSX.Element {
  const [entries, setEntries] = useState<DiaryEntry[]>([])
  const [selectedDate, setSelectedDate] = useState<string | null>(null)
  const [content, setContent] = useState<string>('')
  const [loading, setLoading] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [genDate, setGenDate] = useState<string | null>(null)
  const [msg, setMsg] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)

  const [pendingSnapshots, setPendingSnapshots] = useState<string[]>([])

  const loadList = useCallback(async () => {
    try {
      const res = await ackemClient.diaryList()
      setEntries((res.entries as DiaryEntry[]))
      setPendingSnapshots((res as { pendingSnapshots: string[] }).pendingSnapshots)
    } catch (e) {
      setError(String(e))
    }
  }, [])

  useEffect(() => {
    void loadList()
  }, [loadList])

  // 监听自动生成事件
  useEffect(() => {
    const off = ackemClient.onDiaryAutoGenerated((payload: { date: string; type: string; pendingCount?: number }) => {
      loadList()
      if (payload.type === 'reunion') {
        setMsg(`🌙 重逢日记已自动生成 — ${formatDate(payload.date)}`)
      } else if (payload.pendingCount && payload.pendingCount > 0) {
        setMsg(`日记已补写 — ${formatDate(payload.date)} · 还有 ${payload.pendingCount} 篇待补写`)
      }
    })
    return () => off?.()
  }, [loadList])

  const selectDiary = useCallback(async (date: string) => {
    setSelectedDate(date)
    setLoading(true)
    setError(null)
    try {
      const res = await ackemClient.diaryRead(date)
      if (res.ok) {
        setContent((res as { ok: true; content: string }).content)
      } else {
        setError((res as { ok: false; error: string }).error)
        setContent('')
      }
    } catch (e) {
      setError(String(e))
      setContent('')
    } finally {
      setLoading(false)
    }
  }, [])

  const handleGenerate = useCallback(async (date?: string) => {
    const target = date ?? new Date().toISOString().slice(0, 10)
    setGenerating(true)
    setGenDate(target)
    setMsg(null)
    setError(null)
    try {
      const res = await ackemClient.diaryGenerate({ date: target, force: true })
      if (res.ok) {
        setMsg(date ? `${date} 日记已补写` : '日记已生成')
        await loadList()
        setSelectedDate(target)
        await selectDiary(target)
      } else {
        setError(res.reason ?? '生成失败')
      }
    } catch (e) {
      setError(String(e))
    } finally {
      setGenerating(false)
      setGenDate(null)
    }
  }, [loadList, selectDiary])

  // 选中日记的元数据
  const selectedEntry = useMemo(
    () => entries.find(e => e.date === selectedDate),
    [entries, selectedDate]
  )

  return (
    <div className="flex min-h-0 min-w-0 flex-1">
      {/* 左侧：日期列表 */}
      <div className="w-[220px] shrink-0 border-r border-surface-inset flex flex-col bg-surface">
        <div className="px-3 py-3 border-b border-surface-inset space-y-2">
          <button
            onClick={() => handleGenerate()}
            disabled={generating}
            className="w-full rounded-lg bg-accent px-3 py-2 text-xs font-medium text-white hover:opacity-90 disabled:opacity-50 transition-opacity"
          >
            {generating && genDate === new Date().toISOString().slice(0, 10) ? '生成中…' : '生成今日日记'}
          </button>
          {pendingSnapshots.length > 0 && (
            <div className="border-t border-surface-inset pt-2">
              <p className="text-[11px] text-ink-muted mb-1.5 px-1">可补写的日记</p>
              <div className="max-h-[200px] overflow-y-auto space-y-1">
                {pendingSnapshots.map(date => (
                  <button
                    key={date}
                    onClick={() => handleGenerate(date)}
                    disabled={generating}
                    className="w-full text-left px-2 py-1 rounded text-[11px] text-ink-muted hover:bg-surface-raised hover:text-accent transition-colors disabled:opacity-50 flex justify-between items-center"
                  >
                    <span>{formatDate(date)}</span>
                    {generating && genDate === date ? (
                      <span className="text-accent">生成中…</span>
                    ) : (
                      <span className="text-ink-muted/50">补写</span>
                    )}
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* 已有日记列表 */}
        <div className="flex-1 overflow-y-auto">
          {entries.length === 0 ? (
            <p className="px-3 py-6 text-xs text-ink-muted text-center">暂无日记</p>
          ) : (
            entries.map((e) => {
              const isReunion = e.type === 'reunion'
              return (
                <button
                  key={e.date}
                  onClick={() => selectDiary(e.date)}
                  className={`w-full text-left px-3 py-2.5 text-xs border-b border-surface-inset transition-colors ${
                    selectedDate === e.date
                      ? 'bg-accent/10 text-accent font-medium'
                      : 'text-ink hover:bg-surface-raised'
                  }`}
                >
                  <div className="flex items-center gap-1.5 truncate">
                    {isReunion && <span className="text-xs shrink-0" title={tierLabel(e.tier)}>🌙</span>}
                    <span className="truncate">{formatDate(e.date)}</span>
                  </div>
                  {isReunion && e.tier && (
                    <div className="text-[10px] text-ink-muted/60 mt-0.5 ml-4">
                      {tierLabel(e.tier)}{e.gapHours ? ` · ${gapText(e.gapHours)}` : ''}
                    </div>
                  )}
                </button>
              )
            })
          )}
        </div>
      </div>

      {/* 右侧：日记内容 */}
      <div className="flex-1 min-w-0 overflow-y-auto bg-surface">
        {msg && (
          <div className="mx-4 mt-3 rounded-lg bg-accent/10 border border-accent/20 px-3 py-2 text-xs text-accent">
            {msg}
          </div>
        )}
        {error && (
          <div className="mx-4 mt-3 rounded-lg bg-red-50 border border-red-200 px-3 py-2 text-xs text-red-600">
            {error}
          </div>
        )}

        {!selectedDate && !loading && (
          <div className="flex items-center justify-center h-full text-xs text-ink-muted">
            选择一篇日记查看
          </div>
        )}

        {loading && (
          <div className="flex items-center justify-center h-full text-xs text-ink-muted">
            加载中…
          </div>
        )}

        {selectedDate && !loading && content && (
          <div className="px-6 py-4 max-w-2xl">
            <div className="flex items-center gap-2 mb-1">
              <h1 className="text-lg font-semibold text-ink">
                {formatDate(selectedDate)}
              </h1>
              {selectedEntry?.type === 'reunion' && (
                <span className="text-xs px-2 py-0.5 rounded-full bg-amber-100 text-amber-700 border border-amber-200">
                  🌙 {tierLabel(selectedEntry.tier)}
                  {selectedEntry.gapHours ? ` · ${gapText(selectedEntry.gapHours)}` : ''}
                </span>
              )}
            </div>
            <div
              className="mt-3 diary-content"
              dangerouslySetInnerHTML={{ __html: renderMarkdown(content) }}
            />
          </div>
        )}
      </div>
    </div>
  )
}
